### PR TITLE
Fix Instance() method of Singleton classes

### LINKED ISSUE #148: MacOS - Gazebo: Cannot Add Model to World because simulation is not running
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Even if a user starts `gazebo` from the terminal, the GUI gets launched, but apparently no simulation is running. This has been already reported in https://github.com/RoboStack/ros-noetic/issues/279, but with @nunoguedelha we reproduced it without any ROS involved.

### PR DESCRIPTION
**Pull request by traversaro**
In particular, make sure that all the Instance() methods of the same class always use the same instantiation.

# 🦟 Bug fix

Fixes https://github.com/conda-forge/gazebo-feedstock/issues/148 .

## Summary

This should fix all the cases in which multiple instances of a Singleton classes were observed, as for example in conda-forge/macOS build of Classic Gazebo (see https://github.com/conda-forge/gazebo-feedstock/issues/148#issuecomment-1249496093). The fix was inspired from https://github.com/gazebosim/gz-sim/issues/1725 and from the related PRs:
* https://github.com/gazebosim/gz-common/pull/451
* https://github.com/gazebosim/gz-rendering/pull/734

Thanks a lot to @azeey for suggesting the correct fix in https://github.com/conda-forge/gazebo-feedstock/pull/152#issuecomment-1275198706 .

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: gazebo/common/SingletonT.hh [hunk 1]
```diff
@@ -33,7 +33,7 @@ template <class T>
 class SingletonT
 {
   /// \brief Get an instance of the singleton
-  public: static T *Instance()
+  public: static T *Instance() GAZEBO_DEPRECATED(11.0)
```
Comment (azeey) [inline gazebo/common/SingletonT.hh:53]: Not sure if we need to deprecate this. I think the issue is that we shouldn't be inheriting from `SingletonT`. I'd prefer updating the class documentation stating how it should be used than deprecating it. Perhaps we can also add a deprecated `SingletonT` constructor. I think that would only emit a warning if the class is inherited

**Review by azeey — COMMENTED** [review]
Sorry for the delay in reviewing this. I have one comment regarding deprecation, otherwise, LGTM!

File: gazebo/common/SingletonT.hh (hunk 1 above)
Comment (traversaro) [reply gazebo/common/SingletonT.hh:53]: The basic idea is that this would print a warning if anyone was calling `SingletonT<Type>::Instance` in downstream code for one of the two reason:
* There was a class that inherited from `SingletonT<Type>`, without overriding `Instance`
* Even if an `Instance` in the derived class existed, the instance method of the base class was explicitly called for some reason, like ` `SingletonT<Type>::Instance()` 

Just preventing people from inheriting that class is not sufficient, as someone could call `SingletonT<Type>::Instance()` in two different compilation unit and/or libraries, with confusing behaviours.

Anyhow, I totally agree that this should be documented better in the Singleton class, I will do this.

Comment (traversaro) [reply gazebo/common/SingletonT.hh:53]: I tried to add some docs in https://github.com/gazebosim/gazebo-classic/pull/3269/commits/ff8269550c124a97b2ad73d90716703188565a43 . Given all the problems that this kind of class created, we could also consider to just document that the class is there for backward compatibility, and discourage future use.

Comment (azeey) [reply gazebo/common/SingletonT.hh:53]: Thanks, the documentation looks good. I would also be in favor of discouraging future use. @scpeters are we okay with deprecating a function in a stable release? I'm leaning toward yes because this causes bugs that are hard to find. 

> Just preventing people from inheriting that class is not sufficient, as someone could call SingletonT<Type>::Instance()  in two different compilation unit and/or libraries, with confusing behaviours.

That's a fair point. If anyone calls `SingletonT<T>::Instance()` instead of `T::Instance` anywhere, we still risk getting duplicate symbols.

**Comment by traversaro** [comment]
What is your opinion regarding merging this @scpeters @azeey ? We just hit a regression involving this patch in conda-forge (see https://github.com/conda-forge/gazebo-feedstock/issues/161), to avoid this in the future it would be great if we could get this eventually in an official release.

**Review by azeey — APPROVED** [review]
+1 for merging.

File: gazebo/common/SingletonT.hh (hunk 1 above)
Comment (scpeters) [reply gazebo/common/SingletonT.hh:53]: yes, we can deprecate this

**Review by scpeters — COMMENTED** [review]
thank you, this looks like a good set of changes

I'm rerunning Ubuntu CI and then it will be ready for merge, though I may need to do some testing with ROS before releasing this

File: gazebo/common/SingletonT.hh (hunk 1 above)
Comment (traversaro) [reply gazebo/common/SingletonT.hh:53]: Great, thanks!

**Comment by traversaro** [comment]
> I'm rerunning Ubuntu CI and then it will be ready for merge, though I may need to do some testing with ROS before releasing this

Sure, we can also just wait for the ROS tests before even merging this PR, I am not particulary in a hurry on this one. I am just afraid that at some point the problem that affected conda-forge macOS builds also started to affect other builds (for example homebrew builds as soon as a new version of Apple Clang is released).

**Review by scpeters — APPROVED** [review]
