### PR TITLE
Regression test for distortion leak fix

### LINKED ISSUE #2527: Last camera's distortion affects previous cameras' distortions
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2527)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See the following world for example, where the first camera appears to have barrel distortion even though it was supposed to be pincushion. Swapping the order of models in the world makes both cameras be pincushion.

~~~
<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="default">

    <include>
      <uri>model://sun</uri>
    </include>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
              <bounce>
                <restitution_coefficient>1.0</restitution_coefficient>
                <threshold>0</threshold>
              </bounce>
              <contact>
                <ode>
                  <max_vel>10000</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
          </surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Grey</name>
            </script>
          </material>
        </visual>
      </link>
    </model>

    <model name="ball">
      <allow_auto_disable>false</allow_auto_disable>
      <pose>-1 0 1 0 0 0</pose>
      <static>false</static>
      <link name="link">
        <inertial>
          <mass>0.026</mass>
          <!-- inertia based on solid sphere 2/5 mr^2 -->
          <inertia>
            <ixx>1.664e-5</ixx>
            <iyy>1.664e-5</iyy>
            <izz>1.664e-5</izz>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyz>0</iyz>
          </inertia>
        </inertial>
        <collision name="collision">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
          <surface>
            <bounce>
              <restitution_coefficient>1.0</restitution_coefficient>
              <threshold>0</threshold>
            </bounce>
            <contact>
              <ode>
                <max_vel>10000</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
        </visual>
      </link>
    </model>

    <model name="camera_pincushion">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="pincushion">
        <sensor type="camera" name="camera_pincushion">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>0.1</k1>
              <k2>0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <model name="camera_barrel">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="barrel">
        <sensor type="camera" name="camera_barrel">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>-0.1</k1>
              <k2>-0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>-0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <include>
      <pose>-1.5 0 1 0 1.57 0</pose>
      <uri>model://checkerboard_plane</uri>
    </include>
  </world>
</sdf>
~~~

### PR DESCRIPTION
**Pull request by WilliamLewww**
Closes #2527 - Last camera's distortion affects previous cameras' distortions
Adds regression tests to #3033 - Distortion camera initialization fix

### CODE REVIEW

File: test/regression/2527_distortion_leak.cc [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+  {
+    common::Time::MSleep(10);
+  }
+
+  unsigned int diffMax = 0, diffSum = 0;
+  double diffAvg = 0.0;
+
+  this->ImageCompare(imgNormal, imgBarrel, width, height, 3,
+                     diffMax, diffSum, diffAvg);
+  EXPECT_NE(diffSum, 0u);
```
Comment (ahcorde) [inline test/regression/2527_distortion_leak.cc]: According with the [official docs](https://google.github.io/googletest/reference/assertions.html): `EXPECT_THAT(value,matcher)`

```suggestion
  EXPECT_NE(0u, diffSum);
```

**Review by ahcorde — DISMISSED** [review]

File: test/regression/2527_distortion_leak.cc [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+                  const std::string &_format)
+{
+  std::lock_guard<std::mutex> lock(mutex);
+  pixelFormat = _format;
+  memcpy(_imageDest, _image, _width * _height * _depth);
+  *_imageCounter += 1;
+}
+
+/////////////////////////////////////////////////
+// \brief Test for issue #2527
```
Comment (scpeters) [inline test/regression/2527_distortion_leak.cc]: I believe you took the suggestion from https://github.com/osrf/gazebo/issues/2527#issuecomment-870123099 and have adapted the [CheckDistortion test from camera_sensor.cc](https://github.com/osrf/gazebo/blob/9cd47a0398da3c596e9dedc660cf1b1bb211118e/test/integration/camera_sensor.cc#L695). I think this is a good approach, and it would be worth adding a comment to that effect

Comment (scpeters) [reply test/regression/2527_distortion_leak.cc]: thanks for adding the comment in https://github.com/osrf/gazebo/pull/3044/commits/d0788d3a39910b41003aa83528b3254c3232d80e

I'm noticing that the camera parameters are different than the `CheckDistortion` test though. I'll review it a bit more closely to ensure the expectations make sense

Comment (scpeters) [reply test/regression/2527_distortion_leak.cc]: I just opened the test world and looked at the images, and the 12x12 resolution is too low in my opinion

distortion_test_original

I recompiled camera_sensor.cc with a `world->Save("/tmp/saved.world");` call after the camera sensors have been spawned in the `CheckDistortion` test and applied those changes to the test world in https://github.com/scpeters/gazebo/commit/c997c6bbb42bd4fa0036dc73fc56e86cf7317ed3 and was able to see the distortion more clearly:

distortion_test_320x240

I recommend changing the test world to use these parameters and updating the body of the test to more closely match the `CheckDistortion` test, such as matching the variable names where reasonable to make it easier to compare the tests in a tool like `meld`. You don't need to add the 4th camera that `CheckDistortion` has, I think 3 are enough

Comment (WilliamLewww) [reply test/regression/2527_distortion_leak.cc]: Good catch! A 12x12 image is really impractical and would be too blocky to handle tests. I updated the camera resolution and updated the test code to match more similarly with the `CheckDistortion` test.

**Review by scpeters — APPROVED** [review]
