### PR TITLE
Improvements to WideAngleCamera LensFlare bug fix

### LINKED ISSUE #3273: Wide angle lens flare occlusion bug
From external collaborator:

We have been noticing some issues with wideangle​ cameras in gazebo not always rendering the lens flares even when the sun is in clear sight. I added some print statements in LensFlare.cc​ and I can see that the issue is that FirstContact​ (called [here](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/LensFlare.cc#L325)) will often return true for intersection even when nothing is actually in between the camera and light source, which results in the scale​ shader uniform getting cleared.

I combined elements of gazebo's lensflare_plugin.world​ and  heightmap.world​ to make an easy testing environment that demonstrates this issue. Please see the attached screenshots. The first shows a wideangle camera and a normal camera side-by-side, but the wideangle camera does not have a visible flare. The second screenshot shows the two cameras arbitrarily rotated to find an orientation that correctly produces the lens flare in both. I have also attached the test world - try it out yourself and rotate around the cameras to see how things change. You can also try removing the heightmap, which seems to help a bit, but the problem doesn't fully go away.

Any ideas why the lens flare occlusion checking isn't working very well with wideangle cameras?

lensflare_test_world_broken_wideangle

lensflare_test_world_working_wideangle

<details><summary>lensflare_plugin.world</summary>

```xml
<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="default">

  <!-- Light Source -->
  <light type="directional" name="sun">
    <cast_shadows>true</cast_shadows>
    <pose>0 0 0 0.0 0.0 0.0</pose>
    <diffuse>1.0 1.0 1.0 1.0</diffuse>
    <specular>0.2 0.2 0.2 1</specular>
    <direction>-1.0 0.0 -0.2</direction>
  </light>

    <!-- A ground plane -->
    <include>
      <uri>model://ground_plane</uri>
    </include>

    <model name="heightmap">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <heightmap>
              <uri>file://media/materials/textures/heightmap_bowl.png</uri>
              <size>129 129 10</size>
              <pos>0 0 0</pos>
            </heightmap>
          </geometry>
        </collision>
        <visual name="visual_abcedf">
          <geometry>
            <heightmap>
              <use_terrain_paging>false</use_terrain_paging>
              <texture>
                <diffuse>file://media/materials/textures/dirt_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <texture>
                <diffuse>file://media/materials/textures/grass_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <texture>
                <diffuse>file://media/materials/textures/fungus_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <blend>
                <min_height>2</min_height>
                <fade_dist>5</fade_dist>
              </blend>
              <blend>
                <min_height>4</min_height>
                <fade_dist>5</fade_dist>
              </blend>
              <uri>file://media/materials/textures/heightmap_bowl.png</uri>
              <size>129 129 10</size>
              <pos>0 0 0</pos>
            </heightmap>
          </geometry>
        </visual>
      </link>
    </model>

    <!-- camera model with lens flare plugin -->
    <model name="camera_lensflare">
      <static>true</static>
      <pose>0 1.5 5.2 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <geometry>
            <box>
              <size>0.1 0.1 0.1</size>
            </box>
          </geometry>
        </visual>
        <sensor name="camera_sensor_lensflare" type="camera">
          <camera>
            <horizontal_fov>0.78539816339744828</horizontal_fov>
            <image>
              <width>320</width>
              <height>240</height>
            </image>
            <clip>
              <near>0.1</near>
              <far>100</far>
            </clip>
          </camera>
          <always_on>1</always_on>
          <update_rate>25</update_rate>
          <plugin name="lensflare" filename="libLensFlareSensorPlugin.so"/>
        </sensor>
      </link>
    </model>

    <!-- wide-angle camera model with lens flare plugin -->
    <model name="wide_angle_camera_lensflare">
      <static>true</static>
      <pose>0 2 5.2 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <geometry>
            <box>
              <size>0.1 0.1 0.1</size>
            </box>
          </geometry>
        </visual>
        <sensor name="camera" type="wideanglecamera">
          <camera>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
              <width>320</width>
              <height>240</height>
            </image>
            <clip>
              <near>0.1</near>
              <far>100</far>
            </clip>
            <lens>
              <type>gnomonical</type>
              <scale_to_hfov>true</scale_to_hfov>
              <cutoff_angle>1.5707</cutoff_angle>
              <env_texture_size>512</env_texture_size>
            </lens>
          </camera>
          <always_on>1</always_on>
          <update_rate>25</update_rate>
          <visualize>true</visualize>
          <plugin name="lensflare" filename="libLensFlareSensorPlugin.so"/>
        </sensor>
      </link>
    </model>

  </world>
</sdf>
```

</details>

## To reproduce:

```
gazebo --verbose lensflare_plugin.world
```

Press `Ctrl + t` to bring up the topic window, scroll down to the `gazebo.msgs.ImageStamped` section, and double click on the 2 topic names to bring up the image display window. You'll see that lens flare is visible in the regular camera view but not the wide angle camera view

### PR DESCRIPTION
**Pull request by mogumbo**
# 🦟 Bug fix

Fixes #3273

## Summary
This PR improves an existing bug fix branch. Test with and without this PR by running `gazebo --verbose worlds/lensflare_wideangle_cam.world` and look at the various camera images in Topic Visualization.

Additionally, I tried posing the cameras and obstacles in that world file many different ways. Lens flares appear to behave as they should.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: gazebo/rendering/LensFlare.cc [hunk 1]
```diff
@@ -279,19 +283,41 @@ namespace gazebo
           pos.y /= pos.w;
           // check if light is visible
           if (std::fabs(pos.x) <= 1 &&
-              std::fabs(pos.y) <= 1 && pos.z > abs(pos.w))
+              std::fabs(pos.y) <= 1 && pos.z > -abs(pos.w))
           {
+            // The ogreEnvCamera and wideAngleDummyCamera used here both
+            // transform from gazebo z-up coords to Ogre y-up coords. If the
```
Comment (mogumbo) [inline gazebo/rendering/LensFlare.cc:289]: In retrospect, describing this as "transform from gazebo z-up coords to Ogre y-up coords" might not be accurate. Any insight into what this transform is really doing would be appreciated. It can be found here https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/rendering/Camera.cc#L1585-L1586 and here https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/rendering/WideAngleCamera.cc#L590-L591

I looked at a few ways to reverse one of the transforms seen in the above links. I would have preferred to override one of those methods such that one of the transforms is never made in the first place, but I see didn't an easy way to do this. My current solution probably uses much less code than such an approach.

File: gazebo/rendering/LensFlare.cc [hunk 2]
```diff
@@ -279,19 +283,41 @@ namespace gazebo
           pos.y /= pos.w;
           // check if light is visible
           if (std::fabs(pos.x) <= 1 &&
-              std::fabs(pos.y) <= 1 && pos.z > abs(pos.w))
+              std::fabs(pos.y) <= 1 && pos.z > -abs(pos.w))
```
Comment (scpeters) [inline gazebo/rendering/LensFlare.cc:286]: I know this check doesn't match the one done in WideAngleCamera.cc, but I think that was a bug noticed by Matias. I think @iche033 can confirm

Comment (mogumbo) [reply gazebo/rendering/LensFlare.cc:286]: I don't see any difference in behavior in practice. If we set this back to positive, can someone please explain why? If it is inconsistent with the code in WideAngleCamera.cc it should have a comment explaining why.

Comment (scpeters) [reply gazebo/rendering/LensFlare.cc:286]: actually, looking at comparable code in [gz-rendering](https://github.com/gazebosim/gz-rendering/blob/27c186911b3043450bc429261b78a3fd1e9d71ea/ogre/src/OgreLensFlarePass.cc#L409-L414), it seems like maybe it should be as Terry has changed it here `z > -abs(w)`?

and should it be `fabs(w)`?

**Review by scpeters — APPROVED** [review]
I'll merge this into the `ZFix` branch and then follow up with further changes there. Thanks for fixing it!
