### PR TITLE
Check for nullptr in TopicManager::ConnectPubToSub

### LINKED ISSUE #2875: Gazebo9 - transport failure during ConnectPubToSub call
## Exception: 
```bash
request_publisher: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::transport::Publication; typename boost::detail::sp_member_access<T>::type = gazebo::transport::Publication*]: Assertion `px != 0' failed.
```

## Stack Trace:
```bash
Process terminating with default action of signal 6 (SIGABRT): dumping core
==27141==    at 0x6AD4FB7: raise (raise.c:51)
==27141==    by 0x6AD6920: abort (abort.c:79)
==27141==    by 0x6AC6489: __assert_fail_base (assert.c:92)
==27141==    by 0x6AC6501: __assert_fail (assert.c:101)
==27141==    by 0x52D76E2: boost::shared_ptr<gazebo::transport::Publication>::operator->() const [clone .isra.61] [clone .part.62] (shared_ptr.hpp:734)
==27141==    by 0x52D7A2A: operator-> (TopicManager.cc:283)
==27141==    by 0x52D7A2A: gazebo::transport::TopicManager::ConnectPubToSub(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<gazebo::transport::SubscriptionTransport>) (TopicManager.cc:282)
==27141==    by 0x52C33A5: gazebo::transport::ConnectionManager::OnRead(boost::shared_ptr<gazebo::transport::Connection>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (ConnectionManager.cc:496)
==27141==    by 0x52C434C: operator() (mem_fn_template.hpp:280)
==27141==    by 0x52C434C: operator()<boost::_mfi::mf2<void, gazebo::transport::ConnectionManager, boost::shared_ptr<gazebo::transport::Connection>, const std::__cxx11::basic_string<char>&>, boost::_bi::rrlist1<const std::__cxx11::basic_string<char>&> > (bind.hpp:398)
==27141==    by 0x52C434C: operator()<const std::__cxx11::basic_string<char>&> (bind.hpp:1306)
==27141==    by 0x52C434C: boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, gazebo::transport::ConnectionManager, boost::shared_ptr<gazebo::transport::Connection>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list3<boost::_bi::value<gazebo::transport::ConnectionManager*>, boost::_bi::value<boost::shared_ptr<gazebo::transport::Connection> >, boost::arg<1> > >, void, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::invoke(boost::detail::function::function_buffer&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (function_template.hpp:159)
==27141==    by 0x52C4F4F: operator() (function_template.hpp:759)
==27141==    by 0x52C4F4F: gazebo::transport::ConnectionReadTask::execute() (Connection.hh:74)
```
 ## Description
Gazebo transport is failing while setting up a new connection between a new subscriber to an existing publisher on certain topic. 
- This is occurring within `ConnectPubToSub` due to `PublicationPtr publication = this->FindPublication(_topic)` being an uninitliazed `shared_ptr<Publication>`. 
- A possible reason being that `TopicManager::FindPublication` cannot find an existing `Publication` within `TopicManager::advertisedTopics` for the given topic. This might be caused due to an async call to `TopicManager::Init` or `TopicManager::Fini` via `gazebo::transport::init` or `gazebo::transport::fini` within the same process(while loading a plugin maybe?), which seems to clear `TopicManager::advertisedTopics`.
-   If `TopicManager::advertisedTopics` is cleared between a call to `ConnectSubToPub` and `ConnectPubToSub`, the exception will occur.. I have made an attempt to repro the crash with a bit of a hack here -- https://github.com/ojasjoshi/gzserver_transport_failure/blob/main/README.md

- Checking the existence of `PublicationPtr` such as in `ConnectSubToPub` via `TopicManager::UpdatePublications(_pub.topic(), _pub.msg_type())` might help fix this. 

- I am not sure what the purpose of TopicManager::Init() is? What are the best practices to call gazebo::transport::init explicitly?

### PR DESCRIPTION
**Pull request by emersonknapp**
Fixes #2875

This was causing a very occasional crash problem in real runs, and is reliably reproducible by the method shown in https://github.com/osrf/gazebo/issues/2875#issuecomment-822834452 - which case is explicitly forced by the added regression test. Though it's a pathological case, there is nothing illegal about the test's usage of a global, public API, and therefore it needs the protection. 

The crash case of #2875 is particularly bad in that it allows the server process to be crashed by an external process' actions - all it takes is a mis-timed "sub" message to the server.

This issue also exists in Gazebo9 and will need to be backported.

### CODE REVIEW

**Comment by emersonknapp** [comment]
I'm not sure I'll be able to make the regression test reliably fail without the fix - it seems that the Boost assertion isn't doing anything in this test when playing around with it, though it does always crash my example program as mentioned in #2875. 

I'm not sure exactly how to handle the testing for this - I could use input from someone more familiar with gazebo/boost test/build setup.

**Review by ahcorde — APPROVED** [review]

**Comment by j-rivero** [comment]
I have ported the test directly to gazebo11 branch, without the fixes in this PR, to check if the test is failing there:
 * Mac [Build Status](https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2386/)
 * Linux [Build Status](https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/627/)

**Comment by j-rivero** [comment]
> I have ported the test directly to gazebo11 branch, without the fixes in this PR, to check if the test is failing there:
> 
>     * Mac
> 
>     * Linux

I see it crashing in both platforms and on my local machine so I think the test case is valid. After the patch the CI does not display this crashing anymore.

File: test/regression/2875_connect_pub_to_sub_crash.cc [hunk 1]
```diff
@@ -0,0 +1,54 @@
+/*
+ * Copyright (C) 2021 Amazon.com Inc or its affiliates. All rights reserved.
```
Comment (j-rivero) [inline test/regression/2875_connect_pub_to_sub_crash.cc]: Can we please change the copyright to use the same that in the rest of the code? Thanks.
```suggestion
 * Copyright (C) 2021 Open Source Robotics Foundation
```

Comment (emersonknapp) [reply test/regression/2875_connect_pub_to_sub_crash.cc]: The way I understand copyright, this is how it is meant to be done. If somebody from OSRF also writes into the file, they can add a copyright line for OSRF.

Comment (emersonknapp) [reply test/regression/2875_connect_pub_to_sub_crash.cc]: However, it's not a strong opinion - and it probably doesn't matter at all. I think you have write access to the branch if you really think it should be changed.

Comment (j-rivero) [reply test/regression/2875_connect_pub_to_sub_crash.cc]: I don't think that we have a policy on copyright holders anywhere in the Gazebo project so I was just suggestion to do what we have historically doing (a part from embedded pieces, all the files have the copyright assigned  to OSRF) but that does not give me any right to modify your submission. Please feel free to commit the suggestion or not, I will merge this tomorrow anyway. Thanks Emerson.

**Review by j-rivero — APPROVED** [review]
Thanks for the PR and iterations @emersonknapp
